### ISSUE TITLE
[Bug]: crash in MouseListener::sendMouseEvent

### ISSUE THREAD

**Issue by piem** [juce-framework/JUCE#1145]
### Detailed steps on how to reproduce the bug

f2de0f12b0e820ecc2c908d63989e04a7e53de55 in develop introduced a regression causing crashes on various mouse actions such as mouse down on a popup menu.

### What is the expected behaviour?

don't crash

this patch fixes it:

```
diff --git a/modules/juce_gui_basics/components/juce_Component.cpp b/modules/juce_gui_basics/components/juce_Component.cpp
index 0225e714b..d7f6edffb 100644
--- a/modules/juce_gui_basics/components/juce_Component.cpp
+++ b/modules/juce_gui_basics/components/juce_Component.cpp
@@ -123,6 +123,8 @@ public:
     template <typename EventMethod, typename... Params>
     static void sendMouseEvent (HierarchyChecker& checker, EventMethod&& eventMethod, Params&&... params)
     {
+        if (!checker.nearestNonNullParent()) { jassertfalse; return; }^M
+^M
         if (auto* list = checker.nearestNonNullParent()->mouseListeners.get())
         {
             for (int i = list->listeners.size(); --i >= 0;)
```

### Operating systems

macOS

### What versions of the operating systems?

12.6

### Architectures

Other

### Stacktrace

```shell
AddressSanitizer:DEADLYSIGNAL                                                                       
=================================================================                                   
==44202==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000098 (pc 0x0001066c21c8 bp 0x00016b8ac4f0 sp 0x00016b8ac4d0 T0)
==44202==The signal is caused by a UNKNOWN memory access.                                           
==44202==Hint: address points to the zero page.                                                     
    #0 0x1066c21c8 in std::__1::unique_ptr<juce::Component::MouseListenerList, std::__1::default_delete<juce::Component::MouseListenerList> >::get() const unique_ptr.h:291
    #1 0x1060f176c in void juce::Component::MouseListenerList::sendMouseEvent<void (juce::MouseListener::*)(juce::MouseEvent const&)>(juce::HierarchyChecker&, void (juce::MouseListener::*&&)(juce::MouseEvent const&)) juce_Component.cpp:12
6                                                                                                   
    #2 0x1060f4918 in juce::Component::internalMouseUp(juce::MouseInputSource, juce::PointerState const&, juce::Time, juce::ModifierKeys) juce_Component.cpp:2573
    #3 0x1063f124c in juce::MouseInputSourceInternal::sendMouseUp(juce::Component&, juce::PointerState const&, juce::Time, juce::ModifierKeys) juce_MouseInputSource.cpp:140
    #4 0x1063e7c24 in juce::MouseInputSourceInternal::setButtons(juce::PointerState const&, juce::Time, juce::ModifierKeys) juce_MouseInputSource.cpp:185
    #5 0x10610c78c in juce::MouseInputSourceInternal::handleEvent(juce::ComponentPeer&, juce::Point<float>, juce::Time, juce::ModifierKeys, float, float, juce::PenDetails) juce_MouseInputSource.cpp:312
    #6 0x10610bc14 in juce::MouseInputSource::handleEvent(juce::ComponentPeer&, juce::Point<float>, long long, juce::ModifierKeys, float, float, juce::PenDetails const&) juce_MouseInputSource.cpp:609
    #7 0x106374380 in juce::ComponentPeer::handleMouseEvent(juce::MouseInputSource::InputSourceType, juce::Point<float>, juce::ModifierKeys, float, float, long long, juce::PenDetails, int) juce_ComponentPeer.cpp:90
    #8 0x1065df264 in juce::NSViewComponentPeer::sendMouseEvent(NSEvent*) juce_mac_NSViewComponentPeer.mm:787
    #9 0x1065e33f8 in juce::NSViewComponentPeer::redirectMouseUp(NSEvent*) juce_mac_NSViewComponentPeer.mm:669
    #10 0x1065dc730 in void juce::JuceNSViewClass::callOnOwner<void (juce::NSViewComponentPeer::*)(NSEvent*), NSEvent*&>(objc_object*, void (juce::NSViewComponentPeer::*&&)(NSEvent*), NSEvent*&) juce_mac_NSViewComponentPeer.mm:2240
    #11 0x1065b04a8 in juce::JuceNSViewClass::asyncMouseUp(objc_object*, objc_selector*, NSEvent*) juce_mac_NSViewComponentPeer.mm:2245
    #12 0x1065b0654 in juce::JuceNSViewClass::mouseUp(objc_object*, objc_selector*, NSEvent*) juce_mac_NSViewComponentPeer.mm:2269
    #13 0x1aeee7170 in -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:]+0x9fc (AppKit:arm64e+0x1b2170)
    #14 0x1aeee6508 in -[NSWindow(NSEventRouting) sendEvent:]+0x158 (AppKit:arm64e+0x1b1508)        
    #15 0x1aeee54b0 in -[NSApplication(NSEvent) sendEvent:]+0xad8 (AppKit:arm64e+0x1b04b0)          
    #16 0x1af19f0f0 in -[NSApplication _handleEvent:]+0x48 (AppKit:arm64e+0x46a0f0)                 
    #17 0x1aed67004 in -[NSApplication run]+0x278 (AppKit:arm64e+0x32004)                           
    #18 0x105f25fe4 in juce::MessageManager::runDispatchLoop() juce_mac_MessageManager.mm:359       
    #19 0x105f25d2c in juce::JUCEApplicationBase::main() juce_ApplicationBase.cpp:262               
    #20 0x105f259c8 in juce::JUCEApplicationBase::main(int, char const**) juce_ApplicationBase.cpp:240
    #21 0x1047d0d08 in main Main.cpp:187                                                            
    #22 0x10c429088 in start+0x204 (dyld:arm64e+0x5088)                                             
                                                                                                    
==44202==Register values:                                                                           
 x[0] = 0x0000000000000098   x[1] = 0x000000016b8ac3e0   x[2] = 0x0000000000000005   x[3] = 0x000000016b8ab628
 x[4] = 0x0000000000000000   x[5] = 0x0000000000000001   x[6] = 0x0000000117206c20   x[7] = 0x0000000000000001
 x[8] = 0x0000000000000098   x[9] = 0xd8e0cf73b53b00b9  x[10] = 0x000000016b8ac3a0  x[11] = 0x000000016b8ac190
x[12] = 0x000000016b8ac188  x[13] = 0x000000016b8ac180  x[14] = 0x000000016b8ab4e0  x[15] = 0x0000000000000000
x[16] = 0x0000000104632120  x[17] = 0x000000010c9945d0  x[18] = 0x0000000000000000  x[19] = 0x000000016b8ac660
x[20] = 0x000000013b49fc40  x[21] = 0x000000020242e50c  x[22] = 0x000000020242e534  x[23] = 0x0000000000000002
x[24] = 0x000000020243c000  x[25] = 0x0000000000000000  x[26] = 0x000000002bd80025  x[27] = 0x0000000000000000
x[28] = 0x00000000000000fc     fp = 0x000000016b8ac4f0     lr = 0x00000001066c219c     sp = 0x000000016b8ac4d0
AddressSanitizer can not provide additional info.                                                   
SUMMARY: AddressSanitizer: SEGV unique_ptr.h:291 in std::__1::unique_ptr<juce::Component::MouseListenerList, std::__1::default_delete<juce::Component::MouseListenerList> >::get() const
==44202==ABORTING              ```
```

### Plug-in host applications (DAWs) (if applicable)

N/A

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by talaviram** [comment]
@hogliux - This commit introduce this crash:
f2de0f12b0e820ecc2c908d63989e04a7e53de55

**Comment by talaviram** [comment]
Should be fixed with?
https://github.com/juce-framework/JUCE/commit/c1f3d306793e9fe4393aa8d5b5bcff48839e334e

**Comment by tpoole** [comment]
Yes. Thank you for reporting!
