### ISSUE TITLE
[Bug]: Components permanently steal X11 focus when clicked

### ISSUE THREAD

**Issue by nickdowell** [juce-framework/JUCE#1171]
### Detailed steps on how to reproduce the bug

1. Embed a JUCE component in an X11-based application using the `windowIgnoresKeyPresses` flag:
```c++
component->addToDesktop(juce::ComponentPeer::windowIgnoresKeyPresses, hostWindow);
```
2. Run application and verify that application's keyboard shortcuts work.
3. Click on the JUCE component
4. Observe that the application's keyboard shortcuts no longer work.

### What is the expected behaviour?

JUCE Components should not permanently steal keyboard focus when clicked.

The root of the problem appears to be a call to [`juce::LinuxComponentPeer::grabFocus`](https://github.com/juce-framework/JUCE/blob/bbd6ccbc863edec3150e1e024e4fa3f636802596/modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp#L2036-L2053) made by [`juce::LinuxComponentPeer::toFront`](https://github.com/juce-framework/JUCE/blob/bbd6ccbc863edec3150e1e024e4fa3f636802596/modules/juce_gui_basics/native/juce_linux_Windowing.cpp#L263) in [`XWindowSystem::handleButtonPressEvent`](https://github.com/juce-framework/JUCE/blob/bbd6ccbc863edec3150e1e024e4fa3f636802596/modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp#L3545) (see stacktrace). 
Once this happens, the host application stops receiving keyboard events.

I'm not sure if this is the correct fix, but commenting out the `grabFocus` call in `toFront` resolves the issue for me and I have not yet noticed any ill effect in my use case.

### Operating systems

Linux

### What versions of the operating systems?

Linux Mint 20.3

### Architectures

x86_64

### Stacktrace

```shell
#0  juce::XWindowSystem::grabFocus (this=0x555555c39a50, windowH=96468996) at /home/nick/Repos/amsynth/vendor/JUCE/modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp:2049
#1  0x00005555558e6ea0 in juce::LinuxComponentPeer::grabFocus (this=0x5555563972b0) at /home/nick/Repos/amsynth/vendor/JUCE/modules/juce_gui_basics/native/juce_linux_Windowing.cpp:295
#2  0x00005555558e6d6e in juce::LinuxComponentPeer::toFront (this=0x5555563972b0, makeActive=true) at /home/nick/Repos/amsynth/vendor/JUCE/modules/juce_gui_basics/native/juce_linux_Windowing.cpp:265
#3  0x0000555555879c0f in juce::XWindowSystem::handleButtonPressEvent (this=0x555555c39a50, peer=0x5555563972b0, buttonPressEvent=..., buttonModifierFlag=16) at /home/nick/Repos/amsynth/vendor/JUCE/modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp:3540
#4  0x0000555555879d81 in juce::XWindowSystem::handleButtonPressEvent (this=0x555555c39a50, peer=0x5555563972b0, buttonPressEvent=...) at /home/nick/Repos/amsynth/vendor/JUCE/modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp:3558
#5  0x00005555558790e3 in juce::XWindowSystem::handleWindowMessage (this=0x555555c39a50, peer=0x5555563972b0, event=...) at /home/nick/Repos/amsynth/vendor/JUCE/modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp:3322
#6  0x000055555587b319 in juce::XWindowSystem::windowMessageReceive (event=...) at /home/nick/Repos/amsynth/vendor/JUCE/modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp:3909
#7  0x00005555558788fb in <lambda(int)>::operator()(int) const (__closure=0x555556379c00) at /home/nick/Repos/amsynth/vendor/JUCE/modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp:3245
#8  0x0000555555887eeb in std::_Function_handler<void(int), juce::XWindowSystem::initialiseXDisplay()::<lambda(int)> >::_M_invoke(const std::_Any_data &, int &&) (__functor=..., __args#0=@0x7fffffffdb34: 22) at /usr/include/c++/9/bits/std_function.h:300
#9  0x00005555556d25d6 in std::function<void (int)>::operator()(int) const (this=0x555556379c00, __args#0=22) at /usr/include/c++/9/bits/std_function.h:688
#10 0x00005555556c8378 in <lambda()>::operator()(void) const (__closure=0x555556379c00) at /home/nick/Repos/amsynth/vendor/JUCE/modules/juce_events/native/juce_linux_Messaging.cpp:357
#11 0x00005555556c8a86 in std::_Function_handler<void(), juce::LinuxEventLoop::registerFdCallback(int, std::function<void(int)>, short int)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/9/bits/std_function.h:300
#12 0x00005555556981f4 in std::function<void ()>::operator()() const (this=0x555556379da0) at /usr/include/c++/9/bits/std_function.h:688
#13 0x00005555556cdb53 in juce::InternalRunLoop::dispatchPendingEvents (this=0x555555c2f0c0) at /home/nick/Repos/amsynth/vendor/JUCE/modules/juce_events/native/juce_linux_Messaging.cpp:180
#14 0x00005555556c831c in juce::dispatchNextMessageOnSystemQueue (returnIfNoPendingMessages=true) at /home/nick/Repos/amsynth/vendor/JUCE/modules/juce_events/native/juce_linux_Messaging.cpp:340
```

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by David-Else** [comment]
I think this is related: https://forum.cockos.com/showthread.php?p=2851118#post2851118

**Comment by nickdowell** [comment]
> I think this is related: https://forum.cockos.com/showthread.php?p=2851118#post2851118

I don't think so, because I was seeing this issue outside of Reaper.

**Comment by lo-yak** [comment]
Hi, I don't want to create noise here but is there something we can do in order to help to fix this?
It's really, really difficult to work with JUCE-based plugins right now due to this issue.
I'm having the issue with Reaper specifically (KDE/Wayland on Debian 13, so in my case it's XWayland), I can't even play or pause the project while a plugin is focused.
