### ISSUE TITLE
[Bug]: Anchor parser in URL 0e20a6f breaks LV2 x42 plugins loading.

### ISSUE THREAD

**Issue by KottV** [juce-framework/JUCE#1236]
### Detailed steps on how to reproduce the bug

Checkout JUCE after https://github.com/juce-framework/JUCE/commit/0e20a6fdc5c703b10609a84e344288500fae6871
Build AudioPluginHost
Build and/or install x42 plugins https://gareus.org/misc/x42-plugins/  or just https://x42-plugins.com/x42/x42-compressor
Load `Dynamic Compressor Stereo` or any x42 plugin with GUI

### What is the expected behaviour?

Plugin should be loaded with GUI

### Operating systems

Windows, Linux

### What versions of the operating systems?

tested openSUSE TW

### Architectures

x86_64

### Stacktrace

```shell
Thread 1 "AudioPluginHost" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff775a55b in __GI_kill () at ../sysdeps/unix/syscall-template.S:120
120     T_PSEUDO (SYSCALL_SYMBOL, SYSCALL_NAME, SYSCALL_NARGS)
(gdb) bt
#0  0x00007ffff775a55b in __GI_kill () at ../sysdeps/unix/syscall-template.S:120
#1  0x000000000063576e in juce::lv2_host::UiInstance::UiInstance (this=0x1693238, world=..., descriptorIn=0x12bfdb0, args=..., features=0x16901f0, messagesIn=..., map=..., rl=...)
    at ../../../../modules/juce_audio_processors/format_types/juce_LV2PluginFormat.cpp:2621
#2  0x0000000000636a36 in juce::lv2_host::UiInstanceWithSupports::UiInstanceWithSupports (this=0x1693070, world=..., resizeListener=..., touchListener=..., descriptor=0x12bfdb0, args=..., 
    parent=0x3d00090, engineInstance=..., opts=...) at ../../../../modules/juce_audio_processors/format_types/juce_LV2PluginFormat.cpp:2945
#3  0x00000000006371f4 in juce::lv2_host::ConfiguredEditorComponent::ConfiguredEditorComponent (this=0x13048c0, world=..., instance=..., uiDescriptor=..., resizeListenerIn=..., 
    touchListener=..., uiBundleUri=..., opts=...) at ../../../../modules/juce_audio_processors/format_types/juce_LV2PluginFormat.cpp:3056
#4  0x0000000000638955 in juce::lv2_host::Editor::createView (this=0x15b0b10) at ../../../../modules/juce_audio_processors/format_types/juce_LV2PluginFormat.cpp:3407
#5  0x00000000006384dc in juce::lv2_host::Editor::Editor (this=0x15b0b10, worldIn=..., p=..., instanceProviderIn=..., uiDescriptorIn=..., touchListenerIn=..., listenerIn=..., 
    uiBundleUriIn=..., requiredIn=..., optionalIn=...) at ../../../../modules/juce_audio_processors/format_types/juce_LV2PluginFormat.cpp:3376
#6  0x000000000066a1b1 in std::make_unique<juce::lv2_host::Editor, juce::lv2_host::World&, juce::AudioPluginInstance&, juce::lv2_host::InstanceProvider&, juce::lv2_host::UiDescriptor&, juce::lv2_host::TouchListener&, juce::lv2_host::EditorListener&, juce::String&, juce::lv2_host::RequiredFeatures, juce::lv2_host::OptionalFeatures> ()
    at /usr/include/c++/13/bits/unique_ptr.h:1070
#7  0x000000000063be76 in juce::lv2_host::OptionalEditor<true>::createEditor (this=0x12bfda0, world=..., p=..., instanceProviderIn=..., touchListenerIn=..., listenerIn=...)
    at ../../../../modules/juce_audio_processors/format_types/juce_LV2PluginFormat.cpp:4310
#8  0x000000000063d0dc in juce::lv2_host::LV2AudioPluginInstance::createEditor (this=0x12bf7d0) at ../../../../modules/juce_audio_processors/format_types/juce_LV2PluginFormat.cpp:4478
#9  0x00000000005bfb85 in juce::AudioProcessor::createEditorIfNeeded (this=0x12bf7d0) at ../../../../modules/juce_audio_processors/processors/juce_AudioProcessor.cpp:891
#10 0x00000000004a3633 in PluginWindow::createProcessorEditor (processor=..., type=PluginWindow::Type::normal) at ../../Source/Plugins/../UI/../Plugins/../UI/PluginWindow.h:244
#11 0x00000000004a2d53 in PluginWindow::PluginWindow (this=0x151e7f0, n=0x14dd240, t=PluginWindow::Type::normal, windowList=...)
    at ../../Source/Plugins/../UI/../Plugins/../UI/PluginWindow.h:172
#12 0x000000000049cd69 in PluginGraph::getOrCreateWindowFor (this=0x145bff0, node=0x14dd240, type=PluginWindow::Type::normal) at ../../Source/Plugins/PluginGraph.cpp:180
#13 0x00000000004ad1fe in GraphEditorPanel::PluginComponent::mouseUp (this=0x1321020, e=...) at ../../Source/UI/GraphEditorPanel.cpp:266
#14 0x000000000099f74a in juce::Component::internalMouseUp (this=0x1321020, source=..., relativePointerState=..., time=..., oldModifiers=...)
    at ../../../../modules/juce_gui_basics/components/juce_Component.cpp:2555
#15 0x0000000000a69d73 in juce::MouseInputSourceInternal::sendMouseUp (this=0x11f6280, comp=..., pointerState=..., time=..., oldMods=...)
    at ../../../../modules/juce_gui_basics/mouse/juce_MouseInputSource.cpp:140
#16 0x0000000000a6a028 in juce::MouseInputSourceInternal::setButtons (this=0x11f6280, pointerState=..., time=..., newButtonState=...)
    at ../../../../modules/juce_gui_basics/mouse/juce_MouseInputSource.cpp:185
#17 0x0000000000a6a7a5 in juce::MouseInputSourceInternal::handleEvent (this=0x11f6280, newPeer=..., positionWithinPeer=..., time=..., newMods=..., newPressure=0, newOrientation=0, pen=...)
    at ../../../../modules/juce_gui_basics/mouse/juce_MouseInputSource.cpp:313
#18 0x00000000009a2c29 in juce::MouseInputSource::handleEvent (this=0x7fffffffd1e0, peer=..., pos=..., time=1686194870792, mods=..., pressure=0, orientation=0, penDetails=...)
    at ../../../../modules/juce_gui_basics/mouse/juce_MouseInputSource.cpp:610
#19 0x0000000000a26edd in juce::ComponentPeer::handleMouseEvent (this=0x1495f90, type=juce::MouseInputSource::mouse, pos=..., newMods=..., newPressure=0, newOrientation=0, 
    time=1686194870792, pen=..., touchIndex=0) at ../../../../modules/juce_gui_basics/windows/juce_ComponentPeer.cpp:90
#20 0x0000000000a4557d in juce::XWindowSystem::handleButtonReleaseEvent (this=0x11f6460, peer=0x1495f90, buttonRelEvent=...)
    at ../../../../modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp:3591
#21 0x0000000000a44837 in juce::XWindowSystem::handleWindowMessage (this=0x11f6460, peer=0x1495f90, event=...)
    at ../../../../modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp:3323
#22 0x0000000000a467f1 in juce::XWindowSystem::windowMessageReceive (event=...) at ../../../../modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp:3909
#23 0x0000000000a440bf in operator() (__closure=0x1212880) at ../../../../modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp:3245
#24 0x0000000000a5c796 in std::__invoke_impl<void, juce::XWindowSystem::initialiseXDisplay()::<lambda(int)>&, int>(std::__invoke_other, struct {...} &) (__f=...)
    at /usr/include/c++/13/bits/invoke.h:61
#25 0x0000000000a5788e in std::__invoke_r<void, juce::XWindowSystem::initialiseXDisplay()::<lambda(int)>&, int>(struct {...} &) (__fn=...) at /usr/include/c++/13/bits/invoke.h:111
#26 0x0000000000a523f7 in std::_Function_handler<void(int), juce::XWindowSystem::initialiseXDisplay()::<lambda(int)> >::_M_invoke(const std::_Any_data &, int &&) (__functor=..., 
    __args#0=@0x7fffffffd4c4: 5) at /usr/include/c++/13/bits/std_function.h:290
#27 0x000000000089d58a in std::function<void (int)>::operator()(int) const (this=0x1212880, __args#0=5) at /usr/include/c++/13/bits/std_function.h:591
#28 0x00000000008934d9 in operator() (__closure=0x1212880) at ../../../../modules/juce_events/native/juce_linux_Messaging.cpp:357
#29 0x0000000000894318 in std::__invoke_impl<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void(int)>, short int)::<lambda()>&>(std::__invoke_other, struct {...} &) (
    __f=...) at /usr/include/c++/13/bits/invoke.h:61
#30 0x0000000000893de2 in std::__invoke_r<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void(int)>, short int)::<lambda()>&>(struct {...} &) (__fn=...)
    at /usr/include/c++/13/bits/invoke.h:111
#31 0x0000000000893acd in std::_Function_handler<void(), juce::LinuxEventLoop::registerFdCallback(int, std::function<void(int)>, short int)::<lambda()> >::_M_invoke(const std::_Any_data &)
    (__functor=...) at /usr/include/c++/13/bits/std_function.h:290
#32 0x000000000044a45c in std::function<void ()>::operator()() const (this=0x1212b40) at /usr/include/c++/13/bits/std_function.h:591
#33 0x000000000089869b in juce::InternalRunLoop::dispatchPendingEvents (this=0x11f5c80) at ../../../../modules/juce_events/native/juce_linux_Messaging.cpp:180
#34 0x000000000089348c in juce::dispatchNextMessageOnSystemQueue (returnIfNoPendingMessages=false) at ../../../../modules/juce_events/native/juce_linux_Messaging.cpp:340
#35 0x000000000088df92 in juce::MessageManager::runDispatchLoop (this=0x11f5be0) at ../../../../modules/juce_events/messages/juce_MessageManager.cpp:109
#36 0x000000000088d5fb in juce::JUCEApplicationBase::main () at ../../../../modules/juce_events/messages/juce_ApplicationBase.cpp:265
--Type <RET> for more, q to quit, c to continue without paging--
#37 0x000000000088d510 in juce::JUCEApplicationBase::main (argc=1, argv=0x7fffffffd798) at ../../../../modules/juce_events/messages/juce_ApplicationBase.cpp:243
#38 0x00000000004cda80 in main (argc=1, argv=0x7fffffffd798) at ../../Source/HostStartup.cpp:393
```

### Plug-in formats (if applicable)

LV2

### Plug-in host applications (DAWs) (if applicable)

AudioPluginHost or any JUCE host since 0e20a6f

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by KottV** [comment]
Fixed in https://github.com/juce-framework/JUCE/commit/242e93e41ea43e6bc6336ec720033798b29e33bb
Thnx!
