### ISSUE TITLE
Segmentation fault in AudioPluginHost

### ISSUE THREAD

**Issue by shawone** [juce-framework/JUCE#978]
Hi everyone,

I would like report a problem in AudioPluginHost, this is how to reproduce (x86 / osx Big Sur 11.5.2):
- open any plug-in with UI
- righ click -> "Show Debug Log"
- change any plug-in parameter value
- close the Debug log window
- again, change any plugin parameter value

then, I am getting a segmentation fault:
```
#0      0x00000001064f364a in juce::MessageQueue::deliverNextMessage() at /JUCE/modules/juce_events/native/juce_osx_MessageQueue.h:81
#1      0x00000001064f35a6 in juce::MessageQueue::runLoopCallback() at /JUCE/modules/juce_events/native/juce_osx_MessageQueue.h:92
#2      0x00000001064f3298 in juce::MessageQueue::runLoopSourceCallback(void*) at /JUCE/modules/juce_events/native/juce_osx_MessageQueue.h:100
```
I think the following patch could fixed the problem:
```diff
diff --git a/extras/AudioPluginHost/Source/UI/PluginWindow.h b/extras/AudioPluginHost/Source/UI/PluginWindow.h
index 13636d7..716fd5f 100644
--- a/extras/AudioPluginHost/Source/UI/PluginWindow.h
+++ b/extras/AudioPluginHost/Source/UI/PluginWindow.h
@@ -63,6 +63,12 @@ public:
         log.add ("Parameter debug log started");
     }

+   ~PluginDebugWindow() override
+    {
+       for (auto* p : audioProc.getParameters())
+           p->removeListener (this);
+    }
+
     void parameterValueChanged (int parameterIndex, float newValue) override
     {
         auto* param = audioProc.getParameters()[parameterIndex];
```
Thank you

**Comment by ed95** [comment]
Thanks for reporting, this has been fixed in https://github.com/juce-framework/JUCE/commit/469a3523b75ab07e571b1083acffe258ed75c29c.
